version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel
    depends_on:
      mysql_healthcheck:
        condition: service_completed_successfully

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "5000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  mysql_healthcheck:
    image: mysql:8.0
    command: mysqladmin ping -h${DB_HOST} -P${DB_PORT} -u${DB_USERNAME} -p${DB_PASSWORD}
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
