version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    expose:
      - 9000

  web:
    image: nginx:latest
    ports:
      - "81:81"  # Map host port 80 to container port 80
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Custom Nginx configuration
    depends_on:
      - app
